services:
  mysql:
    image: mysql:8.0
    container_name: task_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task
      MYSQL_USER: task
      MYSQL_PASSWORD: root
    ports:
      - "33061:3306"
    volumes:
      - task_mysql_data:/var/lib/mysql

volumes:
  task_mysql_data:
